### ISSUE TITLE
Incorrect scan code constants

### ISSUE THREAD

**Issue by EnumC** [skai2/EDAutopilot#21]
Some keys in the `SCANCODE` dictionary in directinput.py seems to have incorrect abbreviations, which leads to an uncaught exception. Might have to go through the keys and figure out which ones are incorrect or just try a different key for keybind. 

![abbriev](https://user-images.githubusercontent.com/5799869/57587559-84f70b80-74bb-11e9-8e7a-29a87215233d.PNG)

Ref error: `KeyError: 'DIK_XXXXX'`

**Comment by skai2** [comment]
Well pointed out. 

The reason this is happening is because the convert_to_direct_keys dictionary (which handles the conversion from these special abbreviations to the ones used in the SCANCODE dict) is only used when extracting the modifier keys.

If someone were to use one of the modifier keys as a binding by itself, so not as a modifier, we should see the error you highlighted.

It is a simple fix, apply the conversion dictionary for non modifier keys as well. I'll be sure to fix this in the next version and close the issue.
