### ISSUE TITLE
Get an error while launching "DIK_ACUTE"

### ISSUE THREAD

**Issue by biel203** [skai2/EDAutopilot#22]
I'm configured all needed keys, but when i launch autopilot.py, got this error:

```Traceback (most recent call last):                                                                                        File "autopilot.py", line 1, in <module>                                                                                  from dev_tray import tray                                                                                             File "C:\Users\Gabriel\Downloads\EDAutopilot-19.05.09-alpha-22\dev_tray.py", line 3, in <module>                          from dev_autopilot import autopilot, resource_path, get_bindings, clear_input, set_scanner, RELEASE                   File "C:\Users\Gabriel\Downloads\EDAutopilot-19.05.09-alpha-22\dev_autopilot.py", line 374, in <module>                   keys = get_bindings()                                                                                                 File "C:\Users\Gabriel\Downloads\EDAutopilot-19.05.09-alpha-22\dev_autopilot.py", line 353, in get_bindings               binding['key'] = SCANCODE[binding['pre_key']]                                                                       KeyError: 'DIK_ACUTE' ```

But, what the key ACUTE??

**Comment by skai2** [comment]
Hey there,

Acute seems to be an accent key, or something of the sort. I think the script may be detecting that because of a specific language keyboard or something of the sort. (On my keyboard acute is the key to the left of number 1. Also the tilde key)

I plan on adding support for more keys in a future version but at the moment your best bet is to try binding a different key. You autopilot.log should state which funciton is causing the problem (what acute is bound to).

**Comment by biel203** [comment]
I found the solution!
i went into the file (C:\users\(your user name)\appdata\local\Frontier Developments\Elite Dangerous\options\bindings\Custom.3.0.binds), searched for the key named acute and found the game key related. In my case it was the <PrimaryFire>.

If someone has any problems finding those keys shown on the EDAutopilot traceback log, you can look them on this file.

Thanks for the fast replies and nice work!
